#!/usr/bin/env bash
# pre-compact-backup.sh
# PreCompact hook: Preserve key context before compaction
# Saves decisions, file modifications, and task progress

set -euo pipefail

BACKUP_DIR="${CLAUDE_PROJECT_DIR:-.}/.claude/compact-backups"
TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
BACKUP_FILE="$BACKUP_DIR/pre-compact-$TIMESTAMP.md"

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Read stdin (compaction context from Claude Code)
INPUT=$(cat 2>/dev/null || echo "{}")

cat > "$BACKUP_FILE" << ENDOFBACKUP
# Pre-Compaction Context Backup
**Timestamp**: $TIMESTAMP
**Source**: PreCompact hook

## Recent Git Changes
$(git diff --stat HEAD~3..HEAD 2>/dev/null || echo "No git history available")

## Modified Files (last 60 min)
$(find . -type f \( -name "*.ts" -o -name "*.js" -o -name "*.py" -o -name "*.go" -o -name "*.rs" -o -name "*.md" \) -mmin -60 ! -path "*/node_modules/*" ! -path "*/.git/*" ! -path "*/compact-backups/*" 2>/dev/null | head -20 || echo "None detected")

## Current Branch
$(git branch --show-current 2>/dev/null || echo "unknown")

## Uncommitted Changes
$(git status --short 2>/dev/null | head -15 || echo "Clean or not a git repo")

---
*Auto-generated by pre-compact-backup.sh*
ENDOFBACKUP

# Keep only last 5 backups to prevent bloat
ls -t "$BACKUP_DIR"/pre-compact-*.md 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || true

echo "Context backup saved: $BACKUP_FILE"
exit 0
